name: Supabase Snapshot & Docs

on:
  push:
    branches: [ "main" ]
  schedule:
    # 21:00 UTC daily (≈ 02:30 Asia/Kolkata)
    - cron: "0 21 * * *"
  workflow_dispatch: {}

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Install clients
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client jq

      - name: Install Atlas
        run: curl -sSf https://atlasgo.sh | sh

      - name: Verify docker
        run: docker --version

      - name: Generate snapshot + docs
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          SUPABASE_DB_HOST: ${{ secrets.SUPABASE_DB_HOST }}
          SUPABASE_DB_NAME: ${{ secrets.SUPABASE_DB_NAME }}
          SUPABASE_DB_USER: ${{ secrets.SUPABASE_DB_USER }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SB_PROJECT_REF: ${{ secrets.SB_PROJECT_REF }}
          SCHEMAS: public
        run: make report

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Supabase backup & docs (automated)"
          branch: main
          file_pattern: |
            infra/dumps/**
            infra/inventory/**
            infra/docs/**
            supabase/functions/**
